services:
  flaresolverr:
    container_name: flaresolverr
    environment:
      - TZ=Europe/Warsaw
    image: ghcr.io/flaresolverr/flaresolverr:latest
    ports:
      - "8191:8191"
    restart: unless-stopped
  overseerr:
    container_name: overseerr
    environment:
      - TZ=Europe/Warsaw
    image: sctx/overseerr:latest
    ports:
      - "5055:5055"
    volumes:
      - /mnt/rapid/data/arr/overseerr:/app/config
  prowlarr:
    container_name: prowlarr
    environment:
      - PUID=4000
      - PGID=1000
      - TZ=Europe/Warsaw
    image: ghcr.io/hotio/prowlarr:latest
    ports:
      - "9696:9696"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/rapid/data/arr/prowlarr:/config
  qbittorrent:
    container_name: qbittorrent
    environment:
      - PUID=4000
      - PGID=1000
      - TZ=Europe/Warsaw
      - WEBUI_PORT=8085
      - TORRENTING_PORT=6881
    image: lscr.io/linuxserver/qbittorrent:latest
    ports:
      - "8085:8085"
      - "6881:6881"
      - 6881:6881/udp
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/rapid/data/arr/qbittorrent:/config
      - /mnt/main/nas/content/torrents:/data/torrents
  radarr:
    container_name: radarr
    environment:
      - PUID=4000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Warsaw
    image: ghcr.io/hotio/radarr:latest
    ports:
      - "7878:7878"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/rapid/data/arr/radarr:/config
      - /mnt/main/nas/content:/data
  sonarr:
    container_name: sonarr
    environment:
      - PUID=4000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Warsaw
    image: ghcr.io/hotio/sonarr:latest
    ports:
      - "8989:8989"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/rapid/data/arr/sonarr:/config
      - /mnt/main/nas/content:/data
